#pragma once

#define CLK_GATE_NAME "SPLITT"
#define CLK_GATE_BUFF_NAME "SPLITT"
#define DFF_NAME "DFFT"
#define XOR_NAME "XORT"
#define PAD_NAME "PAD"
#define METAL_ROUTING_LAYER_1 "M1"
#define METAL_ROUTING_LAYER_2 "M3"
#define PIN_PAD "a"
#define PIN_IN_1 "a"
#define PIN_IN_2 "b"
#define PIN_CLK "clk"
#define PIN_OUT_SINGLE "q"
#define PIN_FAN_OUT_1 "q0"
#define PIN_FAN_OUT_2 "q1"
